/**
 * ============================================================
 * FILE: src/utils/env.ts
 * PURPOSE: Environment variable loading and credential validation.
 *          Loads API keys and config from multiple sources in priority order,
 *          so users can store credentials in various locations.
 *
 * LOADING PRIORITY (first found wins for each key):
 *   1. process.env (already-set system/CI environment variables — highest priority)
 *   2. .env, .env.local, .env.pr-review-orchestrator, .env.pr-review-orchestrator.local
 *   3. pr-review-orchestrator/init.json (generated by `pr-review-orchestrator init`)
 *   4. pr-review-orchestrator/local.json (legacy local credentials file)
 *   5. pr-review-orchestrator.config.json or pr-review-orchestrator/config.json (legacy)
 *
 * WHY MULTIPLE FILES?
 *   - .env files are the standard for Node.js projects
 *   - init.json is created by the setup wizard (no separate dotenv needed)
 *   - Legacy config files are supported for backward compatibility
 *   - CI environments set keys directly in process.env (no file needed)
 *
 * CREDENTIAL VALIDATION:
 *   isConfiguredValue() filters out placeholder values like "your_api_key_here"
 *   so the system doesn't try to make API calls with template values.
 * ============================================================
 */

import fs from "node:fs/promises";
import path from "node:path";

// ─── File Path Constants ──────────────────────────────────────────────────────

/**
 * List of .env-style files to try loading, in priority order (later files override earlier).
 * Files that don't exist are silently ignored (ENOENT).
 */
const DEFAULT_ENV_FILES = [
  ".env",                              // Standard dotenv file
  ".env.local",                        // Local overrides (typically gitignored)
  ".env.pr-review-orchestrator",       // Tool-specific env file
  ".env.pr-review-orchestrator.local", // Local overrides for the tool (gitignored)
  ".pr-review-orchestrator"            // Alternative tool config file
];

const TOOL_DIR = "pr-review-orchestrator";                                    // Tool config directory name
const INIT_CONFIG_PATH = path.join(TOOL_DIR, "init.json");                   // Main config (created by `init` command)
const LEGACY_LOCAL_CONFIG_PATH = path.join(TOOL_DIR, "local.json");         // Legacy local credentials
const LEGACY_PROJECT_CONFIG_PATH = path.join(TOOL_DIR, "config.json");      // Legacy project config
const LEGACY_CONFIG_FILE = "pr-review-orchestrator.config.json";             // Legacy root-level config file

// ─── Config Interfaces ────────────────────────────────────────────────────────

/**
 * Shape of pr-review-orchestrator/init.json (created by `pr-review-orchestrator init`).
 * Contains provider selection, API keys, and review configuration.
 */
interface InitConfig {
  provider?: string;          // Provider to use (e.g., "multi-agent", "groq")
  selectedProvider?: string;  // Which provider was selected during init (for model mapping)
  model?: string;             // Model name for the selected provider
  review?: {
    includePaths?: string[];  // Paths to include in review (glob patterns)
    failOnSeverity?: string[];// Severity levels that fail CI (e.g., ["critical", "high"])
  };
  apiKeys?: {
    groq?: string;            // Groq API key
    anthropic?: string;       // Anthropic/Claude API key
    gemini?: string;          // Google Gemini API key
    openai?: string;          // OpenAI API key
    ollamaHost?: string;      // Ollama host URL (e.g., "http://localhost:11434")
  };
  repo?: {
    detectedTypes?: string[]; // Detected repo types: ["react", "node", "python", "java"]
    requiredEnv?: string;     // Required environment variable name
  };
}

/**
 * Shape of the legacy pr-review-orchestrator.config.json format.
 * Supported for backward compatibility with older setups.
 */
interface LegacyConfig {
  provider?: string;          // Provider name
  models?: {
    groq?: string;            // Groq model name
    anthropic?: string;       // Anthropic model name
    gemini?: string;          // Gemini model name
    openai?: string;          // OpenAI model name
    ollama?: string;          // Ollama model name
  };
}

// ─── Credential Validation ────────────────────────────────────────────────────

/**
 * Patterns that indicate a placeholder value — not a real credential.
 * These are the kinds of values that appear in .env.example templates.
 * We filter these out so the system doesn't make API calls with template values.
 */
const PLACEHOLDER_PATTERNS = [
  /^your[_-]/i,        // "your_api_key", "your-token"
  /^replace[_-]/i,     // "replace_with_key"
  /^paste[_-]/i,       // "paste_your_key"
  /^add[_-]/i,         // "add_your_api_key"
  /api[_-]?key[_-]?here/i, // "api_key_here", "apiKeyHere"
  /token[_-]?here/i    // "token_here"
];

/**
 * Returns true if `value` is a real configured credential.
 * Returns false if the value is empty, null, or looks like a placeholder.
 *
 * Used throughout the codebase to guard API calls:
 *   if (!isConfiguredValue(process.env.ANTHROPIC_API_KEY)) return fallback;
 *
 * @param value - The env var value to check
 * @returns true if the value appears to be a real credential
 */
export function isConfiguredValue(value: string | undefined | null): boolean {
  if (!value) return false; // undefined, null, or empty string → not configured

  const normalized = value.trim();
  if (!normalized) return false; // Whitespace-only → not configured

  // If the value matches any placeholder pattern, it's a template value
  return !PLACEHOLDER_PATTERNS.some((pattern) => pattern.test(normalized));
}

// ─── File Loaders ─────────────────────────────────────────────────────────────

/**
 * Safely reads and parses a JSON file.
 * Returns null if the file doesn't exist or isn't valid JSON.
 * Used for loading init.json and legacy config files.
 */
async function loadJsonFile<T>(filePath: string): Promise<T | null> {
  try {
    const raw = await fs.readFile(filePath, "utf8");
    return JSON.parse(raw) as T;
  } catch {
    return null; // File missing or invalid JSON — silently return null
  }
}

/**
 * Removes wrapping quotes from a string if present.
 * Handles both single and double quotes.
 * Needed because .env files allow values like: KEY="value" or KEY='value'
 *
 * Examples:
 *   '"hello"' → "hello"
 *   "'world'" → "world"
 *   "plain"   → "plain" (unchanged)
 */
function stripWrappingQuotes(value: string): string {
  if (value.length < 2) return value;

  const first = value[0];
  const last = value[value.length - 1];
  if ((first === `"` && last === `"`) || (first === `'` && last === `'`)) {
    return value.slice(1, -1); // Remove first and last character (the quotes)
  }

  return value;
}

/**
 * Parses a .env file format string into a key-value record.
 *
 * Supports:
 *   - KEY=value           (bare value)
 *   - KEY="value"         (double-quoted)
 *   - KEY='value'         (single-quoted)
 *   - export KEY=value    (bash-style export prefix)
 *   - # comment lines     (ignored)
 *   - blank lines         (ignored)
 *
 * Does NOT support multiline values or variable interpolation.
 *
 * @param content - Raw .env file content as a string
 * @returns Record of KEY → value pairs
 */
function parseEnvFile(content: string): Record<string, string> {
  const values: Record<string, string> = {};

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue; // Skip blank lines and comments

    // Strip "export " prefix (common in bash scripts)
    const normalized = line.startsWith("export ") ? line.slice(7).trim() : line;

    // Find the first "=" separator — everything before is the key, after is the value
    const separatorIndex = normalized.indexOf("=");
    if (separatorIndex <= 0) continue; // No "=" found or key is empty → skip

    const key = normalized.slice(0, separatorIndex).trim();
    const value = stripWrappingQuotes(normalized.slice(separatorIndex + 1).trim());

    if (key) values[key] = value;
  }

  return values;
}

/**
 * Sets the model env var for a given provider if not already set.
 * Called when loading init.json which may specify a model for the selected provider.
 *
 * Example: selectedProvider="groq", model="llama-3.3-70b-versatile"
 *          → sets GROQ_MODEL if not already in process.env
 */
function applyModelToEnv(selectedProvider: string | undefined, model: string | undefined): void {
  if (!selectedProvider || !model) return;

  // Map provider name to the env var that controls its model
  const envKeyMap: Record<string, string> = {
    groq: "GROQ_MODEL",
    anthropic: "ANTHROPIC_MODEL",
    gemini: "GEMINI_MODEL",
    openai: "OPENAI_MODEL",
    ollama: "OLLAMA_MODEL"
  };

  const envKey = envKeyMap[selectedProvider];
  if (envKey && !(envKey in process.env)) {
    process.env[envKey] = model; // Set model env var (don't override if already set)
  }
}

// ─── Config File Loaders ──────────────────────────────────────────────────────

/**
 * Loads pr-review-orchestrator/init.json — the primary config file created by `init`.
 * Sets: PR_REVIEW_PROVIDER, model env vars, and API key env vars.
 * Only sets values that aren't already in process.env (env vars take priority).
 *
 * @returns List of file paths that were successfully loaded
 */
async function loadInitJsonConfig(rootDir: string): Promise<string[]> {
  const filePath = path.join(rootDir, INIT_CONFIG_PATH);
  const config = await loadJsonFile<InitConfig>(filePath);
  if (!config) return []; // File doesn't exist → skip

  // Set provider if not already in environment
  if (config.provider && !("PR_REVIEW_PROVIDER" in process.env)) {
    process.env.PR_REVIEW_PROVIDER = config.provider;
  }

  // Set model env var for the selected provider
  applyModelToEnv(config.selectedProvider, config.model);

  // Set API key env vars from the init config
  const apiKeys = config.apiKeys ?? {};
  const keyMap: Record<string, string | undefined> = {
    GROQ_API_KEY: apiKeys.groq,
    ANTHROPIC_API_KEY: apiKeys.anthropic,
    GEMINI_API_KEY: apiKeys.gemini,
    OPENAI_API_KEY: apiKeys.openai,
    OLLAMA_HOST: apiKeys.ollamaHost
  };

  for (const [envKey, value] of Object.entries(keyMap)) {
    if (value && !(envKey in process.env)) {
      process.env[envKey] = value; // Set only if not already in environment
    }
  }

  return [filePath]; // Return path for logging purposes
}

/**
 * Loads the legacy pr-review-orchestrator.config.json or pr-review-orchestrator/config.json.
 * Only sets provider and model env vars (older format — no API keys stored here).
 * Called for backward compatibility with setups from older versions.
 */
async function loadLegacyConfig(rootDir: string): Promise<void> {
  // Try legacy root-level file first, then fall back to directory-based file
  const config =
    await loadJsonFile<LegacyConfig>(path.join(rootDir, LEGACY_CONFIG_FILE)) ??
    await loadJsonFile<LegacyConfig>(path.join(rootDir, LEGACY_PROJECT_CONFIG_PATH));

  if (!config) return; // Neither file found → skip

  // Set provider if not already in environment
  if (config.provider && !("PR_REVIEW_PROVIDER" in process.env)) {
    process.env.PR_REVIEW_PROVIDER = config.provider;
  }

  // Set model env vars from legacy config
  const models = config.models ?? {};
  const modelMap: Record<string, string> = {
    groq: "GROQ_MODEL",
    anthropic: "ANTHROPIC_MODEL",
    gemini: "GEMINI_MODEL",
    openai: "OPENAI_MODEL",
    ollama: "OLLAMA_MODEL"
  };

  for (const [provider, envKey] of Object.entries(modelMap)) {
    const model = models[provider as keyof typeof models];
    if (model && !(envKey in process.env)) {
      process.env[envKey] = model;
    }
  }
}

/**
 * Loads the legacy pr-review-orchestrator/local.json.
 * This was the local credentials file in older versions.
 * Sets provider and API key env vars from this file.
 * Called for backward compatibility.
 *
 * @returns List of file paths that were successfully loaded
 */
async function loadLegacyLocalConfig(rootDir: string): Promise<string[]> {
  const filePath = path.join(rootDir, LEGACY_LOCAL_CONFIG_PATH);
  const config = await loadJsonFile<InitConfig>(filePath);
  if (!config) return []; // File doesn't exist → skip

  // Set provider if not already in environment
  if (config.provider && !("PR_REVIEW_PROVIDER" in process.env)) {
    process.env.PR_REVIEW_PROVIDER = config.provider;
  }

  // Set API key env vars from legacy local config
  const apiKeys = config.apiKeys ?? {};
  const keyMap: Record<string, string | undefined> = {
    GROQ_API_KEY: apiKeys.groq,
    ANTHROPIC_API_KEY: apiKeys.anthropic,
    GEMINI_API_KEY: apiKeys.gemini,
    OPENAI_API_KEY: apiKeys.openai,
    OLLAMA_HOST: apiKeys.ollamaHost
  };

  for (const [envKey, value] of Object.entries(keyMap)) {
    if (value && !(envKey in process.env)) {
      process.env[envKey] = value;
    }
  }

  return [filePath];
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Loads all project environment files and config JSONs into process.env.
 * Called once at the start of reviewDiff() before any API calls are made.
 *
 * Loading order (first found wins for each key — process.env has highest priority):
 *   1. process.env (already set — untouched, has priority over everything)
 *   2. .env files (in DEFAULT_ENV_FILES order)
 *   3. pr-review-orchestrator/init.json (main init config)
 *   4. pr-review-orchestrator/local.json (legacy local credentials)
 *   5. Legacy config files (pr-review-orchestrator.config.json, etc.)
 *
 * @param rootDir - Project root directory (default: current working directory)
 * @returns List of file paths that were actually loaded (for logging/debugging)
 */
export async function loadProjectEnv(rootDir = process.cwd()): Promise<string[]> {
  const loadedFiles: string[] = [];

  // Step 1: Load all .env-style files in priority order
  for (const fileName of DEFAULT_ENV_FILES) {
    const filePath = path.join(rootDir, fileName);

    try {
      const content = await fs.readFile(filePath, "utf8");
      const parsed = parseEnvFile(content);

      // Only set keys that aren't already in process.env
      // This ensures CI environment variables always take priority over file-based ones
      for (const [key, value] of Object.entries(parsed)) {
        if (!(key in process.env)) {
          process.env[key] = value;
        }
      }

      loadedFiles.push(filePath);
    } catch (error) {
      // ENOENT = file not found — silently skip (most .env files won't exist)
      const code = (error as NodeJS.ErrnoException).code;
      if (code !== "ENOENT") throw error; // Rethrow unexpected errors (permission denied, etc.)
    }
  }

  // Step 2: Load the init.json config (main config from setup wizard)
  loadedFiles.push(...await loadInitJsonConfig(rootDir));

  // Step 3: Load legacy local.json (backward compat)
  loadedFiles.push(...await loadLegacyLocalConfig(rootDir));

  // Step 4: Load legacy config file (backward compat, no return value — no file path needed)
  await loadLegacyConfig(rootDir);

  return loadedFiles; // Return loaded file paths for diagnostics/logging
}
